name: My First example of a workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v7

            - name: List and read files
              run: | 
                echo " My first Github Actions job"
                ls -ltra
                cat README.md
        
            - name: Generate ASCII artwork
              run: |
                cowsay -f dragon "Run for cover, I am a Dragon ... RAWR" >> dragon.txt
                cat dragon.txt


            # - name: List files
            #   run: ls
            
            # - name: Read files
            #   run: cat README.md