name: My First example of a workflow

on: [push]

jobs:
    first_job:
        runs-on: debian-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v7
            
            - name: Install cowsay program
              run: sudo apt install cowsay -y
            
            - name: Generate ASCII artwork
              run: |
                cowsay -f dragon "Run for cover, I am a Dragon ... RAWR" >> dragon.txt

            - name: Test File exists
              run: grep -i "dragon" dragon.txt

            - name: Read file
              run: cat dragon.txt
            
            - name: Checkout Repo Files
              run: ls