
name: Exploring vars and secrets

# on: push
# This is workflow level env var
on:
  schedule:
    - cron: "*/5 * * * *"

env:
  CONTAINER_REGISTRY: docker.io

jobs:
  docker_job:
    # THis is job level env var
    env:
      IMAGE_NAME: github-actions-nginx
    runs-on: ubuntu-latest
    steps:
# We will enable the env vars at each level
      - name: Dcoker build
        run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Dokcer Login
        # # This is step level env var
        # env:
        #   DOCKER_PASSWORD: s3cUrePaSsw0rd
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker publish
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_IMAGE: github-actions-nginx
        run: echo docker push $DOCKER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest
        
  deploy_job:
    needs: docker_job
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: github-actions-nginx
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest